"""add metaData to User model

Revision ID: ae64c782f043
Revises: 5f9c9312c9e0
Create Date: 2021-07-07 15:16:35.249066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae64c782f043'
down_revision = '5f9c9312c9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('metaData', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'metaData')
    # ### end Alembic commands ###
